class APITopics:
    get_drinks = "get_drinks"
    get_ingredientsForDrink = "get_ingredientsForDrink"
    get_ingredientsList = "get_ingredientsList"
    get_servo = "get_servo"
    get_allservos = "get_allservos"
    set_servo = "set_servo"
    light_on = "light_on"
    light_off = "light_off"
    ring = "ring"
    doseDrink = "doseDrink"
    cleanMe = "cleanMe"
    dryMe = "dryMe"
    openAllValves = "openAllValves"
    closeAllValves = "closeAllValves"

class HardwareTopics:
    light_on = "light_on"
    light_off = "light_off"
    arm_out = "arm_out"
    arm_in ="arm_in"
    arm_position = "arm_position"
    scale_readout = "scale_readout"
    scale_tare = "scale_tare"
    pump_start = "pump_start"
    pump_stop = "pump_stop"
    valve_open = "valve_open"
    valve_close = "valve_close"
    valve_dose = "valve_dose"
    all_valve_open = "all_valve_open"
    all_valve_close = "all_valve_close"
    finger = "finger"
    ping = "ping"
    clean_and_exit = "clean_and_exit"
    cleanMe = "cleanMe"
    dryMe = "dryMe"
    reset = "reset"


